apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PGAdmin
metadata:
  name: pgadmin
spec:
  users:
  - username: admin@pgadmin.postgres-operator.svc
    role: Administrator
    passwordRef:
      name: pgadmin-user-admin
      key: password
  dataVolumeClaimSpec:
    accessModes:
    - "ReadWriteOnce"
    resources:
      requests:
        storage: 1Gi
  serverGroups:
  - name: supply
    postgresClusterSelector: {}