apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-dev
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi9-16.8-2516
  postgresVersion: 16
  shutdown: false

  config:
    parameters:
      max_parallel_workers: 2
      max_worker_processes: 2
      shared_buffers: 256MB
      work_mem: 4MB
      archive_timeout: 300

  dataSource:
    postgresCluster:
      clusterName: hippo
      repoName: repo1
      # options:
      #   - --type=time
      #   - --target="2023-08-02 21:50:13"

  instances:
    - name: pga
      replicas: 1
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi9-2.54.2-2516      
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi

  monitoring:
    pgmonitor:
      exporter: {}
