apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo-dr
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.6-2
  postgresVersion: 16
  shutdown: false

  instances:
    - name: pga
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.54.1-0     
      manual:
        repoName: repo1
        options:
        - --type=full
      global:
        log-level-console: info
        repo1-retention-full-type: time
        repo1-retention-full: "7"   
        start-fast: "y"     
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 10Gi

  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 256MB
          work_mem: 4MB
          archive_timeout: 120

  monitoring:
    pgmonitor:
      exporter:
        image: {}

  customReplicationTLSSecret:
    name: hippo-dr-repl-tls-custom
  customTLSSecret:
    name: hippo-dr-tls-custom
  
  standby:
    enabled: true
    host: hippo-primary
    port: 5432
