apiVersion: postgres-operator.crunchydata.com/v1beta1 
kind: PGUpgrade 
metadata: 
  name: hippo-upgrade 
spec: 
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi9-17.4-2516
  postgresClusterName: hippo 
  fromPostgresVersion: 16
  toPostgresVersion: 17
  toPostgresImage: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi9-17.5-2520