apiVersion: postgres-operator.crunchydata.com/v1beta1 
kind: PGUpgrade 
metadata: 
  name: hippo-upgrade 
spec: 
  image: registry.developers.crunchydata.com/crunchydata/crunchy-upgrade:ubi8-5.7.3-0 
  postgresClusterName: hippo 
  fromPostgresVersion: 16
  toPostgresVersion: 17
  toPostgresImage: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-17.2-2