apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.4-2
  #image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-16.6-2
  #image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-17.2-2  
  postgresVersion: 16
  shutdown: false

  instances:
    - name: pga
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi

  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.53.1-0
      #image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.54.1-0      
      # restore:
      #   enabled: true
      #   repoName: repo1
      #   options:
      #     - --type=time
      #     - --target="2023-08-02 21:50:13"
      manual:
        repoName: repo1
        options:
        - --type=full
      global:
        log-level-console: info
        repo1-retention-full-type: time
        repo1-retention-full: "7"   
        start-fast: "y"     
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * 0"
          differential: "0 1 * * 3"
          incremental: "0 1 * * 1,2,4,5,6"          
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi

  patroni:
    dynamicConfiguration:
      failsafe_mode: true
      #synchronous_mode: true
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 256MB
          work_mem: 4MB
          archive_timeout: 120

  monitoring:
    pgmonitor:
      exporter: {}

  # service:
  #   type: LoadBalancer

  # users:
  #   - name: appuser
  #     databases:
  #       - appdev
  #       - appuat

  # databaseInitSQL:
  #   key: init.sql
  #   name: hippo-init-sql

  # customReplicationTLSSecret:
  #   name: hippo-repl-tls-custom
  # customTLSSecret:
  #   name: hippo-tls-custom
  
  # standby:
  #   enabled: false
  #   host: hippo-dr-primary
  #   port: 5432
